on:
  pull_request_review:
    branches: [main, develop]
    types: [submitted]
jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    outputs:
      output1: ${{ steps.publish.outputs.out }}
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build
        run: npm ci
      - run: npm run build --if-present
        env:
          # Add your environment variables here
          NEXT_PUBLIC_ENVIRONMENT: 'Devnet'
          NEXT_PUBLIC_SENTRY_DSN: 'https://cd10a90d7ae74502a1bd0400b14799f6@o1057883.ingest.sentry.io/6605624'
          NEXT_PUBLIC_MAINTENANCE: 'false'
      - run: npm run export --if-present
      - name: Publish
        id: publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'stkatom-ui' # e.g. 'my-project'
          directory: 'out' # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: echo random-url ${{ steps.publish.outputs.url }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Here's the deployment link - ${{ steps.publish.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
